project_id = "ai-site-editor"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false